version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: udemy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./sites:/sites