version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: udemy-nginx-rp
    ports:
      - "8888:8888"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/ssl:/etc/nginx/ssl
#      - ./sites:/sites